### ISSUE TITLE
Add support for querying organizational trails

### ISSUE THREAD

**Issue by xen0l** [flosell/trailscraper#101]
In setups, which use AWS Organizations, it's common to use organizational trail. Trailscrapper should support downloading logs from such layout. The layout differs in that account_id is prefixed by organization_id.

**Comment by flosell** [comment]
Thanks for the feedback! Agreed, this would be very helpful. 
I might work on this soon if I have the time, but I'm also very happy to accept PRs on this. First point  to look would probably be [`s3_download.py`](https://github.com/flosell/trailscraper/blob/master/trailscraper/s3_download.py) and the [AWS Docs on CloudTrail Log Files](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-find-log-files.html)

**Comment by flosell** [comment]
Implemented and released in [0.6.1](https://github.com/flosell/trailscraper/releases/tag/0.6.1). See the [`README.md`](https://github.com/flosell/trailscraper#download-some-logs-in-organisational-trails) for details.
